# Generated by Django 4.1.1 on 2022-09-20 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermodel',
            old_name='display_phone_number',
            new_name='sender',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='phone_number_id',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='wa_id',
        ),
        migrations.AddField(
            model_name='usermodel',
            name='message_id',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='gpt_response',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='incoming_msg',
            field=models.CharField(max_length=500),
        ),
    ]
